spring.application.name=auth-service
server.port=8094
spring.datasource.url=jdbc:mysql://localhost:3306/bd_festival_auth?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Agrega esto a tu application.properties actual
api.base-url=http://localhost:9090

# ¡Crucial! La misma clave del API Gateway
jwt.secret=esta_es_mi_compleja_clave_secreta_para_el_festival_2026