server:
  port: 9090

spring:
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          # ¡OJO! Esta clave secreta tiene que ser EXACTAMENTE la misma 
          # que usemos en tu microservicio de Auth para crear el token.
          secret-key: esta_es_mi_compleja_clave_secreta_para_el_festival_2026

  cloud:
    gateway:
      routes:
        # 1. Seguridad (El guardia de la entrada)
        - id: auth-service
          uri: http://localhost:8094  
          predicates:
            - Path=/auth/**

        # 2. Gestión de Usuarios
        - id: usuario-service
          uri: http://localhost:8091  
          predicates:
            - Path=/usuarios/**

        # 3. Lineup: Artistas
        - id: artista-service
          uri: http://localhost:8092
          predicates:
            - Path=/artistas/**

        # 4. Lineup: Escenarios
        - id: escenario-service
          uri: http://localhost:8093
          predicates:
            - Path=/escenarios/**

        # 5. Programación de Shows
        - id: presentacion-service
          uri: http://localhost:8095
          predicates:
            - Path=/presentaciones/**

        # 6. Favoritos / Mi Horario
        - id: itinerario-service
          uri: http://localhost:8096  
          predicates:
            - Path=/itinerarios/**
            
        # 7. carrito
        - id: compra-service
          uri: http://localhost:8097  
          predicates:
            - Path=/compras/**

        # 8. Pagos
        - id: pago-service
          uri: http://localhost:8098
          predicates:
            - Path=/pagos/**