spring.application.name=itinerario-service
server.port=8096

# Conexión a BD
spring.datasource.url=jdbc:mysql://localhost:3306/bd_itinerarios?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Liquibase
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URLs para validación interna entre microservicios (Tráfico Este-Oeste)
api.base-url=http://localhost:9090
api.usuario.exists=http://localhost:8091/usuarios/exists/%s
api.presentacion.exists=http://localhost:8095/presentaciones/exists/%s
api.presentacion.detalle=http://localhost:8095/presentaciones/%s

# Trazabilidad y Logs limpios
logging.level.com.festival=INFO
logging.file.name=logs/itinerario-service.log

# Formato limpio para la consola
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n
# Formato limpio para el bloc de notas (.log)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n


jwt.secret=esta_es_mi_compleja_clave_secreta_para_el_festival_2026

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

